### ISSUE TITLE
Problems when converting to new syntax

### ISSUE THREAD

**Issue by Jasperav** [kaandedeoglu/KDCircularProgress#44]
Hello, I am fairly new to coding so maybe I am missing something. I was using this extension for a little app I made, nothing special. It worked great in Xcode 7.3.1. However, I converted it to xCode 8 to syntax 3.0 I think. Now, I can not build or run my app. I get these errors https://postimg.org/image/foy1cjhd1/c54503f1/ (in the picture). Can you help me out? Thank you.

**Comment by kaandedeoglu** [comment]
@Jasperav Hello, you should update to the latest version, which is `Swift 3.0` compatible. If you're using `Cocoapods`, then the version is `1.5.0`. If you're adding the sources manually, then you should update it with the version that is on the `master` branch.

**Comment by Jasperav** [comment]
Thank you, it solved all problems except for one:
https://postimg.org/image/hpttgnsof/
If there is a fix for this I am very grateful :)

**Comment by kaandedeoglu** [comment]
No problem. It's weird because it builds perfectly fine on my machine.

On a different note, I've actually took the opportunity and decided to change the `setColors` function signature to better match with the `Grand Renaming` that happened with `Swift 3` - so if you update to version `1.5.2`, the new signature is as follows: `progress.set(colors: .yellow, .white)`. I hope this fixes the problems. Please let me know!

**Comment by Jasperav** [comment]
Wow! It works now!! Thank you very much :)
